# train_valid, test
pipeline: ['train_valid']
# pipeline: ['train_valid']
gpus: 2
epochs: 100
seed: 31

add_sources:
  # load_ontology, load ddi
  type: ["vocab", "pmd"]
  data_path: ["/home/gzzhan/projects/ComplexView_V2/newdata/voc_final.pkl",
              "/home/gzzhan/data/MIMIC3/gamenet/pmd.npy"]

model:
  name: "DMCL"
  save_path: ""
  dim: 512
  criterion: "InfoNCE"
  t: 1
  metric: []

data:
  path: "/home/gzzhan/data/MIMIC3/gamenet/hot_diag_med.npy"
  # 决定数据组织的方式，the input of medication recommendation is diagnose, output is medication
  #                   the input of diagnose prediction is diagnose or what
  target: "cl_pretrain" 
  need_single: False
  num_workers: 20
  shuffle: True
  batch_size: 8
  split:
    train_ratio: 0.99
    valid_ratio: 0.001
    test_ratio: 0.001

automatic_optimization: True

output: /output/

Callbacks: 
  EarlyStopping:
    monitor: train_loss
    min_delta: 0.00
    patience: 20
    verbose: true
    mode: min
  ModelCheckpoint:
    monitor: train_loss
    mode: min

optimizer:
  Adam:
    # momentum : 0.96
    lr: !!float 5e-4
    weight_decay: !!float 1e-5

mlflow:
  experiment: "CL_pretrain"
  # experiment: "test"
  run_name: "test"
  