pipeline: ['train_valid']
gpus: 1
epochs: 1
seed: 31

add_sources:
  # load_ontology, load ddi
  type: ["vocab"]
  data_path: ["/home/gzzhan/projects/ComplexView_V2/newdata/voc_final.pkl"]

model:
  name: "PMD"
  load_path: ""
  batch_size: 1
  criterion: "CE"
  metric: ["f1","jaccard","PRAUC"]

data:
  path: "/home/gzzhan/projects/ComplexView_V2/newdata/records_final.pkl"
  # 决定数据组织的方式，the input of medication recommendation is diagnose, output is medication
  #                   the input of diagnose prediction is diagnose or what
  target: "med_recommend" 
  need_single: False
  num_workers: 20
  shuffle: true
  split:
    train_ratio: 0.05
    valid_ratio: 0.05
    test_ratio: 0.9

automatic_optimization: False

output: /output/

Callbacks: 
  # EarlyStopping:
  #   monitor: val_loss
  #   min_delta: 0.00
  #   patience: 20
  #   verbose: true
  #   mode: min
  ModelCheckpoint:
    monitor: val_loss
    mode: max

optimizer:
  type: Adam
  momentum : 0.96
  lr: !!float 3e-4
  weight_decay: !!float 1e-5

mlflow:
  experiment: "MedRecommend"
  run_name: "test"
  